export const GET_TESTCASE = "GET_TESTCASE";
export const GET_TESTCASES = "GET_TESTCASES";
export const TESTCASE_LOADING = "TESTCASE_LOADING";

export const GET_GROUP = "GET_GROUP";
export const GET_GROUPS = "GET_GROUPS";
export const GROUP_LOADING = "GROUP_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const USER_LOADING = "USER_LOADING";

export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const PROJECT_LOADING = "PROJECT_LOADING";

export const GET_ROLE = "GET_ROLE";
export const GET_ROLES = "GET_ROLES";
export const ROLE_LOADING = "ROLE_LOADING";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROJECT_SETTINGS = "GET_PROJECT_SETTINGS";
export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const CLEAR_SETTINGS = "CLEAR_SETTINGS";

export const GET_DEVICES = "GET_DEVICES";
export const GET_DEVICE = "GET_DEVICE";
export const DEVICE_LOADING = "DEVICE_LOADING";
export const CLEAR_DEVICES = "CLEAR_DEVICES";

export const GET_SIMULATORS = "GET_SIMULATORS";
export const GET_SIMULATOR = "GET_SIMULATOR";
export const SIMULATOR_LOADING = "SIMULATOR_LOADING";

export const GET_BROWSERS = "GET_BROWSERS";
export const GET_BROWSER = "GET_BROWSER";
export const BROWSER_LOADING = "BROWSER_LOADING";

export const GET_OFFICES = "GET_OFFICES";

export const GET_MOBILE_OS = "GET_MOBILE_OS";
