export const GET_TESTCASE = "GET_TESTCASE";
export const GET_TESTCASES = "GET_TESTCASES";
export const TESTCASE_LOADING = "TESTCASE_LOADING";

export const GET_GROUPS = "GET_GROUPS";
export const GROUP_LOADING = "GROUP_LOADING";
